---
  name: Install and configure tomcat server for deployment
  hosts: nodes
  remote_user: root

  tasks:
   - name: Update system package
     apt:
      upgrade: yes
      update_cache: yes
        
   - name: Install Java
     apt:
       name: openjdk-11-jdk
       state: present

   - name: Create Tomcat User
     user:
      name: tomcat

   - name: Create Tomcat Group
     group:
      name: tomcat

   - name: Create tomcat directory
     file:
      path: "/opt/tomcat"
      owner: tomcat
      group: tomcat
      mode: 755
      recurse: yes

   - name: Download Tomcat and unarchive 
     unarchive:
      src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.72//bin/apache-tomcat-9.0.72.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

   - name: Start tomcat server
     command: sh /opt/tomcat/bin/startup.sh

   - name: allow tcp connections
     command: sudo ufw allow 8080/tcp
      
     
